name: Build and Push
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USER }}" --password-stdin
      - name: Build & Push
        run: |
          docker build -t ${{ secrets.DOCKER_USER }}/backend ./students-app/backend
          docker push ${{ secrets.DOCKER_USER }}/backend
